ngrams:
- and infidels the
- for the global
- not unlike the
- have in the
- this is the
- the role what
- win over the
- the way forward
- i see the
- is the way
- the coming days
- the sermons under
- the past scribbled
- in the eyes
- the eyes of
- dead the position
- in the past
- laden dead the
- the initial round
- in the coming
- unlike the archbishop
- vision of the
- the position of
- of the role
- the global al
- the prophet mohammed
- in the initial
- cartoon of the
- of the prophet
- portrayal of the
- the archbishop of
- infidels the sermons
story:
  date: 2011-05-05
  id: 2011-05-05-job-application
  text: 'With Osama Bin Laden dead, the position of figurehead for the global Al Qaeda
    franchise is vacant. I would like to put myself forward to fill this important
    role. It is true that I do not believe in Allah, have never handled a Kalashnikov,
    and, indeed, have in the past scribbled a blasphemous cartoon of the Prophet Mohammed
    (see here and below). No doubt these things will count against me in the initial
    round of interviews, which I understand will be taking place in some remote mountain
    fastness in the coming days. But I have every confidence that I will be able to
    win over the wild-eyed nutters and gun-toting beardy persons with my unique vision
    of the role. What Al Qaeda desperately needs, I will argue, is an injection of
    woolly Church of England-style cardigan-wearing niceness. Instead of all that
    chanting and suicide bombing and beheading, I see the waging of jihad as a matter
    of cups of tea and arrowroot biscuits and seed cake, with a spot of choral evensong
    and a sermon. And instead of all that shouty sermonising packed with threats against
    Jews and infidels, the sermons under my dispensation will be abstruse and windy,
    full of qualifying phrases and equivocation. This is the way forward, or backwards,
    or even sideways, for all these directions are of course equally valid in the
    eyes of Allah, who we should think of as a sort of benign uncle with an unruly
    beard and fantastic hairy eyebrows, not unlike the Archbishop of Canterbury.


    Blasphemous portrayal of the "Prophet" Mohammed'
  title: Job Application
word_count: 262
