ngrams:
- books and the
- and the garden
- the content and
- that among the
- from the library
- it from the
- the s but
- the cinema what
- him among the
- the other week
- other week the
- secretary the other
- the library just
- the normal course
- book on the
- the garden left
- next in the
- among the accompanying
- among the treats
- written in the
- the breast pocket
- the author tells
- wilderness the author
- photograph in the
- in the newspaper
- the newspaper of
- watched at the
- education secretary the
- bleak settings the
- settings the content
- in the normal
- at the cinema
- the accompanying photos
- promising in the
- a wilderness the
- displayed in the
- in the breast
- in the preface
- the preface by
- the treats in
- on the go
- the go as
- in the s
- this book and
- and clean where
story:
  date: 2014-08-02
  id: 2014-08-02-bracing-walks-in-bleak-settings
  text: 'Dear Mr Key, writes a correspondent I have just made up, I know you are a
    constant reader who always has "a book on the go", as they say. It would interest
    me to know how you go about choosing which book you are going to read next.

    In the normal course of things, I would be hard put to give a straightforward
    answer to that question. Like most of us, I suspect, I alight upon books for all
    manner of different reasons, not always rational. Today, however, I can say definitively
    that I decided on my current reading simply because I saw a photograph in the
    newspaper of Michael Gove reading it.

    When he was sacked as Education Secretary the other week, the Grauniad had a double-page
    spread on Gove, much of which was of course devoted to attacking him. Among the
    accompanying photos was one of Gove "at a literary festival", where he was shown
    reading from--the title was clearly visible--The Lost World of British Communism
    by Raphael Samuel, essays written in the 1980s but published in book form (by
    Verso) in 2006.

    I immediately wanted to read this book, and eventually got round to borrowing
    it from the library. Just a few pages in, and it looks very promising. In the
    preface by Samuel''s widow Alison Light, I learn that among the treats in store
    are such details as

    what Communists sang or watched at the cinema; what they wore, (open-necked shirts,
    if they were men, with a pen or pencil prominently displayed in the breast pocket;
    jumper, slacks and ''sensible shoes'' if they were women); how Party members comported
    themselves in public (they were urged to be neat and clean); where they went on
    holiday--if indeed they took holidays--preferring ''bracing walks'' in bleak settings;
    the content and feel of their homes, which were usually uncomfortable, with a
    small shrine of books and the garden left a wilderness, the author tells us, for
    want of ''personal time''.

    I shall report further snippets of interest as I read on. Meanwhile, if any readers
    are able to provide further photographs of Michael Gove reading particular books,
    I will be very grateful.'
  title: Bracing Walks In Bleak Settings
word_count: 366
